idf_component_register(
    SRCS "main.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "ble_filter.c"
         "app_logic.c"
         "app_prefs.c"
         "app_i18n.c"
         "app_time.c"
         "app_ui.c"
         "app_list.c"
         "app_notif_store.c"
         "app_tone.c"
         "app_notif.c"
         "app_shell.c"
         "app_lock.c"
         "app_notif_rule.c"
         "app_ancs.c"
         "app_logs.c"
         "app_net.c"
         "app_net_policy.c"
         "app_web.c"
         "qrcode.c"
         "fonts/lv_font_cjk_12.c"
    INCLUDE_DIRS "."
    REQUIRES bsp nvs_flash esp_netif lwip
             spi_flash driver bt esp_event esp_http_server
    EMBED_FILES "bg_anime.bin" "bg_geek.bin" "bg_ink.bin" "bg_pop.bin"
)
