CREATE TABLE IF NOT EXISTS farms (
  id INT UNSIGNED NOT NULL PRIMARY KEY,
  mac VARCHAR(17) NOT NULL,
  token VARCHAR(64) NOT NULL,
  name VARCHAR(12) NOT NULL DEFAULT '',
  level TINYINT UNSIGNED NOT NULL DEFAULT 1,
  xp SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  coins INT UNSIGNED NOT NULL DEFAULT 80,
  pick TINYINT UNSIGNED NOT NULL DEFAULT 0,
  seeds JSON NOT NULL,
  plots JSON NOT NULL,
  friends JSON NOT NULL,
  updated_at INT UNSIGNED NOT NULL,
  UNIQUE KEY uk_mac (mac),
  UNIQUE KEY uk_token (token),
  KEY idx_updated (updated_at),
  KEY idx_coins (coins)
);

CREATE TABLE IF NOT EXISTS friend_reqs (
  from_id INT UNSIGNED NOT NULL,
  to_id INT UNSIGNED NOT NULL,
  at_sec INT UNSIGNED NOT NULL,
  PRIMARY KEY (from_id, to_id),
  KEY idx_to (to_id)
);

CREATE TABLE IF NOT EXISTS mail (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  to_id INT UNSIGNED NOT NULL,
  from_id INT UNSIGNED NOT NULL,
  kind TINYINT UNSIGNED NOT NULL,
  got SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  at_sec INT UNSIGNED NOT NULL,
  KEY idx_to (to_id, id)
);

CREATE TABLE IF NOT EXISTS steal_cool (
  cool_key VARCHAR(48) NOT NULL PRIMARY KEY,
  at_sec INT UNSIGNED NOT NULL,
  cool_n SMALLINT UNSIGNED NOT NULL
);
